data = {
    0: ('ADONIS', 'https://en.wikipedia.org/wiki/Adonis_blue'),
    1: ('AFRICAN GIANT SWALLOWTAIL', 'https://en.m.wikipedia.org/wiki/Papilio_antimachus'),
    2: ('AMERICAN SNOOT', 'https://en.wikipedia.org/wiki/American_snout'),
    3: ('AN 88', 'https://zoology.fandom.com/ru/wiki/%D0%91%D0%B0%D0%B1%D0%BE%D1%87%D0%BA%D0%B0_%2288%22'),
    4: ('APPOLLO', 'https://en.wikipedia.org/wiki/Apollo_(butterfly)'),
    5: ('ATALA', 'https://en.wikipedia.org/wiki/Eumaeus_atala'),
    6: ('BANDED ORANGE HELICONIAN', 'https://en.wikipedia.org/wiki/Dryadula_phaetusa'),
    7: ('BANDED PEACOCK', 'https://en.wikipedia.org/wiki/Anartia_fatima'),
    8: ('BECKERS WHITE', 'https://en.wikipedia.org/wiki/Pontia_beckerii'),
    9: ('BLACK HAIRSTREAK', 'https://en.wikipedia.org/wiki/Black_hairstreak'),
    10: ('BLUE MORPHO', 'https://en.wikipedia.org/wiki/Morpho_menelaus'),
    11: ('BLUE SPOTTED CROW', 'https://en.wikipedia.org/wiki/Euploea_midamus'),
    12: ('BROWN SIPROETA', 'https://en.wikipedia.org/wiki/Siproeta_epaphus'),
    13: ('CABBAGE WHITE', 'https://en.wikipedia.org/wiki/Pieris_rapae'),
    14: ('CAIRNS BIRDWING', 'https://en.wikipedia.org/wiki/Ornithoptera_euphorion'),
    15: ('CHECQUERED SKIPPER', 'https://butterfly-conservation.org/butterflies/chequered-skipper'),
    16: ('CHESTNUT', 'https://butterfly-conservation.org/moths/the-chestnut'),
    17: ('CLEOPATRA', 'https://butterfly-conservation.org/butterflies/cleopatra'),
    18: ('CLODIUS PARNASSIAN', 'https://en.m.wikipedia.org/wiki/Parnassius_clodius'),
    19: ('CLOUDED SULPHUR', 'https://insectic.com/clouded-sulphur-butterfly/'),
    20: ('COMMON BANDED AWL', 'https://en.wikipedia.org/wiki/Hasora_chromus'),
    21: ('COMMON WOOD-NYMPH', 'https://en.wikipedia.org/wiki/Common_wood-nymph'),
    22: ('COPPER TAIL', 'https://en.m.wikipedia.org/wiki/Lycaena_arota'),
    23: ('CRECENT', 'https://en.wikipedia.org/wiki/Crescentin'),
    24: ('CRIMSON PATCH', 'https://en.wikipedia.org/wiki/Chlosyne_janais'),
    25: ('DANAID EGGFLY', 'https://en.m.wikipedia.org/wiki/Hypolimnas_misippus'),
    26: ('EASTERN COMA', 'https://www.butterflyidentification.com/eastern-comma.htm'),
    27: ('EASTERN DAPPLE WHITE', 'https://www.butterflyidentification.com/dappled-white.htm'),
    28: ('EASTERN PINE ELFIN', 'https://en.wikipedia.org/wiki/Callophrys_niphon'),
    29: ('ELBOWED PIERROT', 'https://en.m.wikipedia.org/wiki/Caleta_elna'),
    30: ('GOLD BANDED', 'https://en.m.wikipedia.org/wiki/Telegonus_cellus'),
    31: ('GREAT EGGFLY', 'https://en.wikipedia.org/wiki/Hypolimnas_bolina'),
    32: ('GREAT JAY', 'https://en.wikipedia.org/wiki/Graphium_eurypylus'),
    33: ('GREEN CELLED CATTLEHEART', 'https://en.m.wikipedia.org/wiki/Parides_childrenae'),
    34: ('GREY HAIRSTREAK', 'https://en.wikipedia.org/wiki/Gray_hairstreak'),
    35: ('INDRA SWALLOW', 'https://en.wikipedia.org/wiki/Papilio_indra'),
    36: ('IPHICLUS SISTER', 'https://en.wikipedia.org/wiki/Adelpha'),
    37: ('JULIA', 'https://en.m.wikipedia.org/wiki/Dryas_iulia'),
    38: ('LARGE MARBLE', 'https://en.wikipedia.org/wiki/Euchloe_ausonides'),
    39: ('MALACHITE', 'https://en.wikipedia.org/wiki/Siproeta_stelenes'),
    40: ('MANGROVE SKIPPER', 'https://en.m.wikipedia.org/wiki/Phocides_pigmalion'),
    41: ('MESTRA', 'https://en.wikipedia.org/wiki/Mycalesis_mestra'),
    42: ('METALMARK', 'https://en.wikipedia.org/wiki/Riodinidae'),
    43: ('MILBERTS TORTOISESHELL', 'https://pictureinsect.com/wiki/Aglais_milberti.html'),
    44: ('MONARCH', 'https://en.wikipedia.org/wiki/Monarch_butterfly'),
    45: ('MOURNING CLOAK', 'https://en.wikipedia.org/wiki/Nymphalis_antiopa'),
    46: ('ORANGE OAKLEAF', 'https://en.wikipedia.org/wiki/Kallima_inachus'),
    47: ('ORANGE TIP', 'https://en.wikipedia.org/wiki/Anthocharis_cardamines'),
    48: ('ORCHARD SWALLOW', 'https://en.m.wikipedia.org/wiki/Papilio_aegeus'),
    49: ('PAINTED LADY', 'https://en.wikipedia.org/wiki/Vanessa_cardui'),
    50: ('PAPER KITE', 'https://en.wikipedia.org/wiki/Idea_leuconoe'),
    51: ('PEACOCK', 'https://en.wikipedia.org/wiki/Aglais_io'),
    52: ('PINE WHITE', 'https://en.wikipedia.org/wiki/Neophasia_menapia'),
    53: ('PIPEVINE SWALLOW', 'https://en.wikipedia.org/wiki/Battus_philenor'),
    54: ('POPINJAY', 'https://en.m.wikipedia.org/wiki/Stibochiona_nicea'),
    55: ('PURPLE HAIRSTREAK', 'https://en.wikipedia.org/wiki/Purple_hairstreak'),
    56: ('PURPLISH COPPER', 'https://en.wikipedia.org/wiki/Lycaena_helloides'),
    57: ('QUESTION MARK', 'https://en.wikipedia.org/wiki/Polygonia_interrogationis'),
    58: ('RED ADMIRAL', 'https://en.wikipedia.org/wiki/Vanessa_atalanta'),
    59: ('RED CRACKER', 'https://en.wikipedia.org/wiki/Hamadryas_amphinome'),
    60: ('RED POSTMAN', 'https://en.wikipedia.org/wiki/Heliconius_erato'),
    61: ('RED SPOTTED PURPLE', 'https://en.wikipedia.org/wiki/Limenitis_arthemis'),
    62: ('SCARCE SWALLOW', 'https://en.wikipedia.org/wiki/Scarce_swallowtail'),
    63: ('SILVER SPOT SKIPPER', 'https://en.wikipedia.org/wiki/Epargyreus_clarus'),
    64: ('SLEEPY ORANGE', 'https://en.wikipedia.org/wiki/Eurema_nicippe'),
    65: ('SOOTYWING', 'https://www.butterfliesoforegon.com/pholisora-catullus'),
    66: ('SOUTHERN DOGFACE', 'https://en.wikipedia.org/wiki/Zerene_cesonia'),
    67: ('STRAITED QUEEN', 'https://en.wikipedia.org/wiki/Queen_(butterfly)'),
    68: ('TROPICAL LEAFWING', 'https://en.wikipedia.org/wiki/Anaea_troglodyta'),
    69: ('TWO BARRED FLASHER', 'https://en.wikipedia.org/wiki/Telegonus_fulgerator'),
    70: ('ULYSES', 'https://en.wikipedia.org/wiki/Papilio_ulysses'),
    71: ('VICEROY', 'https://en.wikipedia.org/wiki/Viceroy_(butterfly)'),
    72: ('WOOD SATYR', 'https://en.wikipedia.org/wiki/Megisto_cymela'),
    73: ('YELLOW SWALLOW TAIL', 'https://en.wikipedia.org/wiki/Papilio_xuthus'),
    74: ('ZEBRA LONG WING', 'https://en.wikipedia.org/wiki/Heliconius_charithonia')
}
